language: java
jdk: openjdk7
before_install:
  - 'export COMMIT_MESSAGE=`curl https://api.github.com/repos/$TRAVIS_REPO_SLUG/git/commits/$TRAVIS_COMMIT |sed -n ''s/.*"message": "\(.*\)",/\1/p''`'
  - '[ $TRAVIS_PULL_REQUEST == false -a $TRAVIS_REPO_SLUG == Wolf480pl/GeoAbstract -a $TRAVIS_BRANCH == master ] && export DEPLOY=true'
install: mvn clean package -DbuildNumber=${TRAVIS_BUILD_NUMBER} -DskipTests=true
after_success:
  - "git clone -b travis `git config --get remote.origin.url` target/travis"
  - "[ $DEPLOY == true ] && mvn deploy --settings target/travis/settings.xml -DbuildNumber=${TRAVIS_BUILD_NUMBER}"
  - "[ $DEPLOY == true ] && echo $COMMIT_MESSAGE |grep -iF [site] && mvn site-deploy --settings target/travis/settings.xml -DbuildNumber=${TRAVIS_BUILD_NUMBER}"

notifications:
    email: false
    webhooks:
      - http://n.tkte.ch/h/1232/y6Iew4Ugv7uWNsuy2jtOwmyg
branches:
  except:
    - travis
    - gh-pages
env:
  global:
    - secure: "Os4HHpatSyil5pQ6JeRnflAYRnO1LjkotCvcwAfpBCQRnkmcvSnLuIHE9ojjhB1Pe9mjKHVEe2FcAr+As5lbonpACokTGTZPBXd7JFlMI5c52aW0GGAWKsLNF8o5XNP+gn52y5mkRG+YfHfbCCQ8dvuD41i4/gayE9yl3FnDcUs="
    - secure: "Nbb64A9OJOjRhJNoNFHbvV87FEX42y8QeS5D01ZWd4z79YLCBjmUjHFivNbqN9vLtde8cLdXuf//BxhKjm/OLSQsxKcmrMe+sy7qYZQJgG7AH2RMosX2pGpGB3aeTfpiarhAj2M+RUcv6zrmNJyk5epLIWlzQOrfjBkRBrqHixI="
    - secure: "GBe+gTtmLY7w6jAK5lMPPL4r07HQig7zE2kBerAqecd9EWYSMGfOCj1Yq0ZM7JcXsku8tKORYeht836BCI507+7k+lJawyG1xtKY6wYBewIYhV1YTtIxuKKHhdNXHf9uPEgWs0ojNqeN3rEhcUA0ydqOZJpd/u+ggsdz3gMbOkI="
