language: java
jdk: openjdk7
before_install: 'export COMMIT_MESSAGE=`curl https://api.github.com/repos/$TRAVIS_REPO_SLUG/git/commits/$TRAVIS_COMMIT |sed -n ''s/.*"message": "\(.*\)",/\1/p''`'
install: mvn clean package -DbuildNumber=${TRAVIS_BUILD_NUMBER} -DskipTests=true
after_success:
  - "git clone -b travis `git config --get remote.origin.url` target/travis"
  - "[[ \"$TRAVIS_BRANCH\" == \"master\" ]] && mvn deploy --settings target/travis/settings.xml"
  - "[[ \"$TRAVIS_BRANCH\" == \"master\" ]] && echo $COMMIT_MESSAGE |grep -iF [site] && mvn site-deploy"

notifications:
    email: false
    webhooks:
      - http://n.tkte.ch/h/1232/y6Iew4Ugv7uWNsuy2jtOwmyg
branches:
  except:
    - travis
    - gh-pages
env:
  global:
    - secure: "GHiCrPAdSkf+5+gWL1bu/oEV276nhs5s7Cs4AzYBVmYah71wYfspPeMSXrJHbbMrdkaSjMkED3B0eUx3XxAzrF1SxkrHGdOUnek6zEIcyiFwwFWyCxHCB/PZRIrzCmZzimBvExKTZATXZJ9QtuM6y3vusq8wInTzNqoaeEfN1q4="
    - secure: "lRFfInpTGSx39soyskFqbs4Bzmzfq9Ab09xX2mL+XgxsZgYHKBAm0vZUYF99V2uNDV9AT7jiKnIDIiP9dbSoOP2Zo07sdI+UNamXGbBH8ShQXZw2xf4n14MQZllpmJHee1/rhOamiGK64pxpRns9AbLj+3HR3a33YKLBadG0ZX4="
    - secure: "GBe+gTtmLY7w6jAK5lMPPL4r07HQig7zE2kBerAqecd9EWYSMGfOCj1Yq0ZM7JcXsku8tKORYeht836BCI507+7k+lJawyG1xtKY6wYBewIYhV1YTtIxuKKHhdNXHf9uPEgWs0ojNqeN3rEhcUA0ydqOZJpd/u+ggsdz3gMbOkI="
